baseURL: https://cheerfulkidsmusic.com/
languageCode: en-us
title: Cheerful Kids Music
theme: hugo-fresh
googleAnalytics: UA-151182278-1 #Put in your tracking code without quotes like this: UA-XXXXXX...
#Disables warningss
disableKinds:
 -taxonomy
 -taxonomyTerm


params:
 # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: 
  navbarlogo:
  # Logo (from static/images/logos/___)
   image: logos/ckmlogo.png
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Cheerful kids and music lessons? <br/> Yes!
    # Hero subtitle (optional)
    subtitle: A fun, unique music appreciation program for children 
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "/about"
    # Hero image (from static/images/___)
    image: illustrations/peanut2.jpg
    # Footer logos (from static/images/logos/clients/___.svg)
    # clientlogos:
    # - systek
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: About Instructor
    url: /about
  - title: Program Details
    url: /program
  - title: Hours & Contact
    url: /contact
  # - title: Sign up
  #   url: /
  #   button: true
  section1:
    title: Fun comes first
    subtitle: but we immerse music theory into the lessons - kids will love it!
    image: instruments.jpg 
  section2:
    title: You're here because you want the best
    subtitle: And we know it
    image: activity1.png 
    features:
    - title: Learn music theory in a fun way
      text: Ability to appreciate music at a young age and grasp theory concepts
      # Icon (from /images/illustrations/icons/___.svg)
      icon: playlist
    - title: Early exposure to classical music 
      text: Get to know music by famous composers such as Mozart, Bach, and Beethoven
      icon: conductor
    - title: Build self-confidence 
      text: Helps improve social, emotional and cognitive skill
      icon: confidence
  # section3:
  #   title: One platform
  #   subtitle: To rule them all
  #   image: illustrations/mockups/app-mockup.png
  #   buttonText: Get started
  #   buttonLink: "#"
  # section4:
  #   title: Our Clients love us!
  #   subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
  #   clients:
  #   - name: Irma Walters
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Accountant
  #     img: 1
  #   - name: John Bradley
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Financial Analyst
  #     img: 2
  #   - name: Gary Blackman
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: HR Manager
  #     img: 3
  section5: false
  footer:
    # Logo (from /images/logos/___)
    logo: ckmlogo_square.png
    # Social Media Title
    # socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    # socialmedia:
    # - link: https://github.com/lucperkins/github-fresh
    #   # Icons are from Font Awesome
    #   icon: github
    # - link: https://dribbble.com/#
    #   icon: dribbble
    # - link: https://facebook.com/#
    #   icon: facebook
    # - link: https://twitter.com/lucperkins
    #   icon: twitter
    # - link: https://bitbucket.org/#
    #   icon: bitbucket
    bulmalogo: false
    quicklinks:
      column1:
        title: "More Information"
        links:
        - text: About Instructor
          link: /about
        - text: Program Details
          link: /program
        - text: Contact
          link: /contact
